#!/usr/bin/env node
// Vendors Lucide icons (ISC license, https://lucide.dev) as inline SVG
// inner-markup strings — the quality.md stage-B icon lock. Re-run to add
// icons; the output file is fully regenerated.
//
// Usage: node scripts/vendor-icons.mjs <outFile.ts> <icon-name> [...]

import { writeFileSync } from "node:fs";

const [out, ...names] = process.argv.slice(2);
if (!out || names.length === 0) {
  console.error("Usage: node scripts/vendor-icons.mjs <outFile.ts> <icon...>");
  process.exit(1);
}

const fetchIcon = async (name) => {
  const res = await fetch(
    `https://unpkg.com/lucide-static@latest/icons/${name}.svg`,
  );
  if (!res.ok) throw new Error(`${name}: HTTP ${res.status}`);
  const svg = await res.text();
  return svg
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .trim()
    .replace(/\n\s*/g, " ");
};

const camel = (n) => n.replace(/-(\w)/g, (_, c) => c.toUpperCase());

const entries = [];
const failed = [];
for (const n of names) {
  try {
    entries.push([camel(n), await fetchIcon(n)]);
    console.log(`ok   ${n}`);
  } catch (e) {
    failed.push(n);
    console.error(`FAIL ${n}: ${e.message}`);
  }
}

const body = entries
  .map(([k, inner]) => `  ${k}: ${JSON.stringify(inner)},`)
  .join("\n");

writeFileSync(
  out,
  `// Generated by scripts/vendor-icons.mjs — do not edit by hand.
// Lucide icons (https://lucide.dev), ISC license. 24×24 viewBox,
// stroke inherited from the wrapping <svg>.
export const ICON_PATHS = {
${body}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`,
);

console.log(`\nWrote ${entries.length} icons → ${out}`);
if (failed.length) {
  console.error(`Missing (fix names and re-run): ${failed.join(", ")}`);
  process.exit(1);
}
